In [1]:
import numpy as np
import pandas as pd

In [69]:
import pandas as pd

# Long dataset with varied sentences
sentences = [
    "The sun sets in the west, casting a golden hue across the sky as the birds return to their nests.",
    "Artificial intelligence is transforming the world by enabling machines to learn and make decisions autonomously.",
    "She enjoys reading science fiction books because they allow her to explore futuristic concepts and new possibilities.",
    "The cat sat on the windowsill, lazily watching the raindrops race down the glass pane.",
    "He plays the guitar every evening, filling the house with melodious tunes that bring a sense of peace.",
    "Machine learning models improve with more data, allowing them to make better predictions and understand patterns.",
    "They traveled to Paris for their vacation, visiting famous landmarks such as the Eiffel Tower and the Louvre Museum.",
    "Cooking is both an art and a science, requiring creativity, precision, and an understanding of flavors.",
    "The rain poured heavily throughout the night, creating a rhythmic sound that lulled everyone to sleep.",
    "Space exploration is advancing rapidly, with scientists working on missions to Mars and beyond.",
    "She practiced yoga every morning, believing it helped her maintain both physical health and mental clarity.",
    "Quantum computing is a fascinating field that has the potential to revolutionize problem-solving in science and technology.",
    "The artist painted a beautiful landscape, capturing the essence of nature with every brushstroke on the canvas.",
    "They watched a thrilling movie last night, filled with unexpected twists and a captivating storyline.",
    "Technology is evolving at an incredible pace, influencing every aspect of human life, from communication to medicine.",
    "The mountain peaks were covered in snow, glistening under the morning sun as hikers prepared for their journey.",
    "He solved the puzzle in just five minutes, impressing everyone with his sharp thinking and problem-solving skills.",
    "They adopted a cute little puppy, instantly falling in love with its playful nature and adorable eyes.",
    "The ocean waves crashed against the shore, creating a soothing melody that resonated with the tranquility of the beach.",
    "She learned a new language in a year, practicing daily and immersing herself in books, movies, and conversations.",
    "The library was filled with books of every genre, offering knowledge and entertainment to avid readers.",
    "He built a treehouse in his backyard, creating a secret hideaway where he could read and dream.",
    "She discovered an ancient artifact while exploring the old ruins, sparking curiosity among archaeologists.",
    "The scientist conducted experiments to understand the effects of climate change on marine ecosystems.",
    "They hiked through the dense forest, listening to the sounds of birds and rustling leaves.",
    "The detective carefully examined the crime scene, searching for clues that could solve the mystery.",
    "He spent hours programming a new application, determined to solve a problem using innovative algorithms.",
    "She wrote in her journal every night, documenting her thoughts, experiences, and dreams for the future.",
    "The little boy watched in awe as the magician performed incredible tricks on stage.",
    "They set up a telescope in the backyard to observe the stars and planets in the night sky.",
    "The chef prepared a delicious five-course meal, impressing the guests with exquisite flavors and presentation.",
    "The athlete trained rigorously for the marathon, pushing his limits to achieve his personal best time.",
    "They planted a vegetable garden, growing fresh tomatoes, cucumbers, and peppers for their kitchen.",
    "The city was bustling with energy, with people rushing to work, street vendors selling food, and cars honking.",
    "She spent the afternoon painting a mural, bringing vibrant colors to an otherwise dull wall.",
    "The pilot skillfully navigated the plane through turbulent weather, ensuring a smooth landing for the passengers.",
    "The musician composed a new symphony, blending classical and modern elements to create a masterpiece.",
    "They organized a surprise birthday party, inviting friends and decorating the venue with balloons and lights.",
    "The historian studied ancient manuscripts, uncovering secrets about lost civilizations.",
    "The doctor worked tirelessly in the hospital, treating patients and saving lives.",
    "The astronaut trained for years before embarking on a mission to the International Space Station.",
    "They designed an innovative gadget that could translate spoken language in real time.",
    "The novelist spent years writing her book, carefully crafting characters and an engaging plot.",
    "The storm raged on outside, with thunderclaps and lightning illuminating the dark sky.",
    "The farmer woke up early to tend to his crops, ensuring they received enough water and care.",
    "The philosopher pondered deep questions about the meaning of life and human existence.",
    "The engineer developed a new AI system that could assist doctors in diagnosing diseases.",
    "The explorer ventured into the Amazon rainforest, discovering rare species of plants and animals.",
    "The teacher inspired students with engaging lessons that made learning fun and exciting.",
    "The firefighter bravely rushed into the burning building, rescuing people trapped inside."
]



In [70]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

import os
story = []
for filename in os.listdir('/Users/shivendragupta/Desktop/Deep Learning/LSTM/data'):
    f = open(os.path.join('/Users/shivendragupta/Desktop/Deep Learning/LSTM/data',filename), errors="ignore")
    corpus = f.read()
    raw_sent = sent_tokenize(corpus)
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

In [6]:
tokenizer.fit_on_texts([sentences])

In [4]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [5]:
tokenizer = Tokenizer(oov_token='<nothing>')

In [7]:
tokenizer.fit_on_texts(sentences)

In [8]:
tokenizer.word_index

{'<nothing>': 1,
 'the': 2,
 'and': 3,
 'a': 4,
 'to': 5,
 'in': 6,
 'with': 7,
 'they': 8,
 'of': 9,
 'that': 10,
 'for': 11,
 'on': 12,
 'an': 13,
 'she': 14,
 'every': 15,
 'is': 16,
 'her': 17,
 'new': 18,
 'he': 19,
 'his': 20,
 'as': 21,
 'their': 22,
 'night': 23,
 'could': 24,
 'sky': 25,
 'science': 26,
 'books': 27,
 'creating': 28,
 'problem': 29,
 'spent': 30,
 'sun': 31,
 'birds': 32,
 'make': 33,
 'learning': 34,
 'understand': 35,
 'both': 36,
 'flavors': 37,
 'everyone': 38,
 'space': 39,
 'morning': 40,
 'solving': 41,
 'technology': 42,
 'nature': 43,
 'watched': 44,
 'filled': 45,
 'incredible': 46,
 'human': 47,
 'life': 48,
 'prepared': 49,
 'five': 50,
 'impressing': 51,
 'little': 52,
 'language': 53,
 'was': 54,
 'backyard': 55,
 'ancient': 56,
 'through': 57,
 'carefully': 58,
 'solve': 59,
 'innovative': 60,
 'up': 61,
 'trained': 62,
 'time': 63,
 'people': 64,
 'ensuring': 65,
 'about': 66,
 'years': 67,
 'engaging': 68,
 'into': 69,
 'the sun sets in the we

In [9]:
tokenized_sentence = tokenizer.texts_to_sequences(sentences)

In [10]:
len(tokenizer.word_index)

521

In [17]:
input_sequences = []
for i in range(1,len(tokenized_sentence)):
    input_sequences.append(tokenized_sentence[:i+1][0])

In [68]:
input_sequences

[[2,
  31,
  120,
  6,
  2,
  121,
  122,
  4,
  123,
  124,
  125,
  2,
  25,
  21,
  2,
  32,
  126,
  5,
  22,
  127],
 [2,
  31,
  120,
  6,
  2,
  121,
  122,
  4,
  123,
  124,
  125,
  2,
  25,
  21,
  2,
  32,
  126,
  5,
  22,
  127],
 [2,
  31,
  120,
  6,
  2,
  121,
  122,
  4,
  123,
  124,
  125,
  2,
  25,
  21,
  2,
  32,
  126,
  5,
  22,
  127],
 [2,
  31,
  120,
  6,
  2,
  121,
  122,
  4,
  123,
  124,
  125,
  2,
  25,
  21,
  2,
  32,
  126,
  5,
  22,
  127],
 [2,
  31,
  120,
  6,
  2,
  121,
  122,
  4,
  123,
  124,
  125,
  2,
  25,
  21,
  2,
  32,
  126,
  5,
  22,
  127],
 [2,
  31,
  120,
  6,
  2,
  121,
  122,
  4,
  123,
  124,
  125,
  2,
  25,
  21,
  2,
  32,
  126,
  5,
  22,
  127],
 [2,
  31,
  120,
  6,
  2,
  121,
  122,
  4,
  123,
  124,
  125,
  2,
  25,
  21,
  2,
  32,
  126,
  5,
  22,
  127],
 [2,
  31,
  120,
  6,
  2,
  121,
  122,
  4,
  123,
  124,
  125,
  2,
  25,
  21,
  2,
  32,
  126,
  5,
  22,
  127],
 [2,
  31,
  120,
  6,
 

In [67]:
max_len = max([len(x) for x in input_sequences])

In [20]:
max_len

20

In [21]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [22]:
padded_seq = pad_sequences(input_sequences,maxlen=max_len)

In [23]:
padded_seq

array([[  2,  31, 120,   6,   2, 121, 122,   4, 123, 124, 125,   2,  25,
         21,   2,  32, 126,   5,  22, 127],
       [  2,  31, 120,   6,   2, 121, 122,   4, 123, 124, 125,   2,  25,
         21,   2,  32, 126,   5,  22, 127],
       [  2,  31, 120,   6,   2, 121, 122,   4, 123, 124, 125,   2,  25,
         21,   2,  32, 126,   5,  22, 127],
       [  2,  31, 120,   6,   2, 121, 122,   4, 123, 124, 125,   2,  25,
         21,   2,  32, 126,   5,  22, 127],
       [  2,  31, 120,   6,   2, 121, 122,   4, 123, 124, 125,   2,  25,
         21,   2,  32, 126,   5,  22, 127],
       [  2,  31, 120,   6,   2, 121, 122,   4, 123, 124, 125,   2,  25,
         21,   2,  32, 126,   5,  22, 127],
       [  2,  31, 120,   6,   2, 121, 122,   4, 123, 124, 125,   2,  25,
         21,   2,  32, 126,   5,  22, 127],
       [  2,  31, 120,   6,   2, 121, 122,   4, 123, 124, 125,   2,  25,
         21,   2,  32, 126,   5,  22, 127],
       [  2,  31, 120,   6,   2, 121, 122,   4, 123, 124, 125,  

In [24]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import *

In [25]:
X = padded_seq[:,:-1]
y = padded_seq[:,-1]

In [64]:
X

array([[  2,  31, 120,   6,   2, 121, 122,   4, 123, 124, 125,   2,  25,
         21,   2,  32, 126,   5,  22],
       [  2,  31, 120,   6,   2, 121, 122,   4, 123, 124, 125,   2,  25,
         21,   2,  32, 126,   5,  22],
       [  2,  31, 120,   6,   2, 121, 122,   4, 123, 124, 125,   2,  25,
         21,   2,  32, 126,   5,  22],
       [  2,  31, 120,   6,   2, 121, 122,   4, 123, 124, 125,   2,  25,
         21,   2,  32, 126,   5,  22],
       [  2,  31, 120,   6,   2, 121, 122,   4, 123, 124, 125,   2,  25,
         21,   2,  32, 126,   5,  22],
       [  2,  31, 120,   6,   2, 121, 122,   4, 123, 124, 125,   2,  25,
         21,   2,  32, 126,   5,  22],
       [  2,  31, 120,   6,   2, 121, 122,   4, 123, 124, 125,   2,  25,
         21,   2,  32, 126,   5,  22],
       [  2,  31, 120,   6,   2, 121, 122,   4, 123, 124, 125,   2,  25,
         21,   2,  32, 126,   5,  22],
       [  2,  31, 120,   6,   2, 121, 122,   4, 123, 124, 125,   2,  25,
         21,   2,  32, 126,   5

In [65]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [28]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y,num_classes=521)

In [40]:
y[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [59]:
model = Sequential()

model.add(Embedding(521,200,input_length=19))
model.add(LSTM(2, return_sequences=True))
model.add(LSTM(2, return_sequences=True))
model.add(LSTM(2, return_sequences=True))
model.add(LSTM(2, return_sequences=True))
model.add(LSTM(2, return_sequences=True))
model.add(LSTM(2, return_sequences=True))
model.add(LSTM(2, return_sequences=True))
model.add(LSTM(2, return_sequences=True))
model.add(LSTM(2))
# model.add(Dense(256, activation='relu')),
model.add(Dense(521, activation='softmax'))

In [60]:
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

In [61]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_17 (LSTM)                  │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_18 (LSTM)                  │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_19 (LSTM)                  │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_20 (LSTM)                  │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_21 (LSTM)                  │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_22 (LSTM)                  │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_23 (LSTM)                  │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_24 (LSTM)                  │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_25 (LSTM)                  │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [62]:
model.fit(X,y,epochs=100)

Epoch 1/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - accuracy: 0.2313 - loss: 6.2552  
Epoch 2/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 1.0000 - loss: 6.2507
Epoch 3/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 6.2460
Epoch 4/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 6.2413
Epoch 5/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 6.2363
Epoch 6/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 6.2313
Epoch 7/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 6.2261
Epoch 8/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 6.2207
Epoch 9/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 6.2151
Epoch 10/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 6.2093
Epoch 11/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 6.2033
Epoch 12/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 1.0000 - 

In [63]:
import time
text = "Artificial intelligence"

for i in range(10):
  # tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]
  # padding
  padded_token_text = pad_sequences([token_text], maxlen=29, padding='pre')
  # predict
  pos = np.argmax(model.predict(padded_token_text))

  for word,index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)
      time.sleep(2)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 351ms/step
Artificial intelligence nests
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
Artificial intelligence nests nests
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
Artificial intelligence nests nests nests
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
Artificial intelligence nests nests nests nests
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
Artificial intelligence nests nests nests nests nests
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
Artificial intelligence nests nests nests nests nests nests
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
Artificial intelligence nests nests nests nests nests nests nests
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
Artificial intelligence nests nests nests nests nests nests nests nests
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
Artificial intelligence nests nests nests nests nests nests nests nests nests
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
Artificial intelligence nests nests nests nests nests nests nests nests nests nests
