In [2]:
import pandas as pd
import numpy as np


In [6]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [8]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [9]:
def initialize_parameters(layer_dims):
  
  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)         

  for l in range(1, L):

    parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
    parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))
      

  return parameters

In [10]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [22]:
def linear_forward(A_prev, W, b):
  
  Z = np.dot(W.T, A_prev) + b
  
  return Z

In [39]:
# Forward Prop
def L_layer_forward(X, parameters):

  A = X
  L = len(parameters) // 2 # number of layers in the neural network
  
  for l in range(1, L+1):
    A_prev = A 
    Wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]
    #print("A"+str(l-1)+": ", A_prev)
    #print("W"+str(l)+": ", Wl)
    #print("b"+str(l)+": ", bl)
    #print("--"*20)

    A = linear_forward(A_prev, Wl, bl)
    #print("A"+str(l)+": ", A)
    #print("**"*20)
          
  return A,A_prev

In [23]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X, parameters)

2


In [16]:
y_hat,A1

(array([[0.32]]),
 array([[1.6],
        [1.6]]))

In [46]:
def update_parameters(parameters, y, y_hat, A1, X):
    learning_rate = 0.001

    # Compute gradients for W2 and b2
    dW2_0 = 2 * (y - y_hat) * A1[0][0]
    dW2_1 = 2 * (y - y_hat) * A1[1][0]
    db2 = 2 * (y - y_hat)

    # Compute gradients for W1 and b1
    dW1_00 = 2 * (y - y_hat) * parameters['W2'][0][0] * X[0][0]
    dW1_01 = 2 * (y - y_hat) * parameters['W2'][0][0] * X[1][0]
    db1_0 = 2 * (y - y_hat) * parameters['W2'][0][0]

    dW1_10 = 2 * (y - y_hat) * parameters['W2'][1][0] * X[0][0]
    dW1_11 = 2 * (y - y_hat) * parameters['W2'][1][0] * X[1][0]
    db1_1 = 2 * (y - y_hat) * parameters['W2'][1][0]

    # Update W2 and b2
    parameters['W2'][0][0] += learning_rate * dW2_0
    parameters['W2'][1][0] += learning_rate * dW2_1
    parameters['b2'][0][0] += learning_rate * db2

    # Update W1 and b1
    parameters['W1'][0][0] += learning_rate * dW1_00
    parameters['W1'][0][1] += learning_rate * dW1_01
    parameters['b1'][0][0] += learning_rate * db1_0

    parameters['W1'][1][0] += learning_rate * dW1_10
    parameters['W1'][1][1] += learning_rate * dW1_11
    parameters['b1'][1][0] += learning_rate * db1_1

    return parameters

In [25]:
update_parameters(parameters,y,y_hat,A1,X)

/var/folders/qx/720g_1z55gg_fwcvggbhs3_w0000gn/T/ipykernel_4628/332058445.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
/var/folders/qx/720g_1z55gg_fwcvggbhs3_w0000gn/T/ipykernel_4628/332058445.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
/var/folders/qx/720g_1z55gg_fwcvggbhs3_w0000gn/T/ipykernel_4628/332058445.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single elemen

In [47]:
parameters

{'W1': array([[0.26420074, 0.35286782],
        [0.26785077, 0.36004351]]),
 'b1': array([[0.02606678],
        [0.02674339]]),
 'W2': array([[0.40156541],
        [0.4210365 ]]),
 'b2': array([[0.42214391]])}

In [48]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.105888, 0.105888],
        [0.105888, 0.105888]]),
 'b1': array([[0.000736],
        [0.000736]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.00736]])}

In [49]:
X = df[['cgpa', 'profile_score']].values[1].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[1][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.11310786, 0.11517068],
        [0.11310786, 0.11517068]]),
 'b1': array([[0.00176741],
        [0.00176741]]),
 'W2': array([[0.12741603],
        [0.12741603]]),
 'b2': array([[0.01658746]])}

In [50]:
X = df[['cgpa', 'profile_score']].values[1].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[1][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.12116643, 0.1255317 ],
        [0.12116643, 0.1255317 ]]),
 'b1': array([[0.00291863],
        [0.00291863]]),
 'W2': array([[0.14378317],
        [0.14408137]]),
 'b2': array([[0.02562262]])}

In [51]:
epochs = 75

loss = []

parameters = initialize_parameters([2,2,1])

for i in range(epochs):
    for j in range(X.shape[0]):
        X = df[['cgpa', 'profile_score']].values[j].reshape(2,1) 
        y = df[['lpa']].values[j][0]

        y_hat,A1 = L_layer_forward(X,parameters)
        y_hat = y_hat[0][0]

        update_parameters(parameters,y,y_hat,A1,X)
        loss.append((y-y_hat)**2)
    print("Loss at "+str(i)+" is " + str(np.mean(loss)))
        

Loss at 0 is 17.414460925244423
Loss at 1 is 16.70919806732515
Loss at 2 is 15.890633443742137
Loss at 3 is 14.959647748439489
Loss at 4 is 13.93342845139755
Loss at 5 is 12.847855922385634
Loss at 6 is 11.753222237355335
Loss at 7 is 10.702653543184963
Loss at 8 is 9.738274250665228
Loss at 9 is 8.882803354039435
Loss at 10 is 8.140069466418147
Loss at 11 is 7.501405363141174
Loss at 12 is 6.952709507228312
Loss at 13 is 6.479222237318521
Loss at 14 is 6.0677846294080355
Loss at 15 is 5.7074824376838755
Loss at 16 is 5.389539302477606
Loss at 17 is 5.1069652902330755
Loss at 18 is 4.854185313841077
Loss at 19 is 4.626722808369847
Loss at 20 is 4.420951193402971
Loss at 21 is 4.233904574297076
Loss at 22 is 4.063134835273135
Loss at 23 is 3.9066035487170523
Loss at 24 is 3.7625996401393884
Loss at 25 is 3.629676088015675
Loss at 26 is 3.506600770577023
Loss at 27 is 3.392317918168799
Loss at 28 is 3.285917595012729
Loss at 29 is 3.1866113215729763
Loss at 30 is 3.0937124394222164
Loss 

In [52]:
parameters

{'W1': array([[0.26673125, 0.35860032],
        [0.26914371, 0.36455483]]),
 'b1': array([[0.02658322],
        [0.02710616]]),
 'W2': array([[0.42544202],
        [0.44686041]]),
 'b2': array([[0.11899605]])}

In [53]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[0][0]
y_hat,A1 = L_layer_forward(X,parameters)
y_hat,y

(array([[4.55148341]]), 4)