In [2]:
import pandas as pd
import numpy as np


In [6]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [8]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [9]:
def initialize_parameters(layer_dims):
  
  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)         

  for l in range(1, L):

    parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
    parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))
      

  return parameters

In [10]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [22]:
def linear_forward(A_prev, W, b):
  
  Z = np.dot(W.T, A_prev) + b
  
  return Z

In [39]:
# Forward Prop
def L_layer_forward(X, parameters):

  A = X
  L = len(parameters) // 2 # number of layers in the neural network
  
  for l in range(1, L+1):
    A_prev = A 
    Wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]
    #print("A"+str(l-1)+": ", A_prev)
    #print("W"+str(l)+": ", Wl)
    #print("b"+str(l)+": ", bl)
    #print("--"*20)

    A = linear_forward(A_prev, Wl, bl)
    #print("A"+str(l)+": ", A)
    #print("**"*20)
          
  return A,A_prev

In [23]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X, parameters)

2


In [16]:
y_hat,A1

(array([[0.32]]),
 array([[1.6],
        [1.6]]))

In [24]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [25]:
update_parameters(parameters,y,y_hat,A1,X)

/var/folders/qx/720g_1z55gg_fwcvggbhs3_w0000gn/T/ipykernel_4628/332058445.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
/var/folders/qx/720g_1z55gg_fwcvggbhs3_w0000gn/T/ipykernel_4628/332058445.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
/var/folders/qx/720g_1z55gg_fwcvggbhs3_w0000gn/T/ipykernel_4628/332058445.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single elemen

In [26]:
parameters

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

In [27]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

2


{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

In [28]:
X = df[['cgpa', 'profile_score']].values[1].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[1][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

2


{'W1': array([[0.11458955, 0.1168776 ],
        [0.11458955, 0.1168776 ]]),
 'b1': array([[0.0019667],
        [0.0019667]]),
 'W2': array([[0.12712927],
        [0.12712927]]),
 'b2': array([[0.13612818]])}

In [29]:
X = df[['cgpa', 'profile_score']].values[1].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[1][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

2


{'W1': array([[0.12339902, 0.12820406],
        [0.1234188 , 0.12822949]]),
 'b1': array([[0.00322519],
        [0.00322802]]),
 'W2': array([[0.14325344],
        [0.14357505]]),
 'b2': array([[0.15236016]])}

In [41]:
epochs = 75

loss = []

parameters = initialize_parameters([2,2,1])

for i in range(epochs):
    for j in range(X.shape[0]):
        X = df[['cgpa', 'profile_score']].values[j].reshape(2,1) 
        y = df[['lpa']].values[j][0]

        y_hat,A1 = L_layer_forward(X,parameters)
        y_hat = y_hat[0][0]

        update_parameters(parameters,y,y_hat,A1,X)
        loss.append((y-y_hat)**2)
    print("Loss at "+str(i)+" is " + str(np.mean(loss)))
        

Loss at 0 is 16.89375409265402
Loss at 1 is 15.949433988745309
Loss at 2 is 15.022482408794724
Loss at 3 is 14.021083662847497
Loss at 4 is 12.952226438994582
Loss at 5 is 11.853963417419804
Loss at 6 is 10.777460546706084
Loss at 7 is 9.770826763783903
Loss at 8 is 8.866374918680322
Loss at 9 is 8.076445995370399
Loss at 10 is 7.397379550803913
Loss at 11 is 6.816711782804073
Loss at 12 is 6.31924342324848
Loss at 13 is 5.890513823226753
Loss at 14 is 5.518170158355264
Loss at 15 is 5.192172672736946
Loss at 16 is 4.9045245174007395
Loss at 17 is 4.648883572229817
Loss at 18 is 4.420200413537219
Loss at 19 is 4.214423327384649
Loss at 20 is 4.028270684459851
Loss at 21 is 3.8590588866903968
Loss at 22 is 3.7045728784475433
Loss at 23 is 3.562968312821647
Loss at 24 is 3.4326970515709743
Loss at 25 is 3.3124498891096823
Loss at 26 is 3.2011120743982358
Loss at 27 is 3.097728427861732
Loss at 28 is 3.0014757237581353
Loss at 29 is 2.911640629611411
Loss at 30 is 2.8276019377889754
Loss 

In [42]:
parameters

{'W1': array([[0.26420074, 0.35286782],
        [0.26785077, 0.36004351]]),
 'b1': array([[0.02606678],
        [0.02674339]]),
 'W2': array([[0.40156541],
        [0.4210365 ]]),
 'b2': array([[0.42214391]])}

In [45]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[0][0]
y_hat,A1 = L_layer_forward(X,parameters)
y_hat,y

(array([[4.55439278]]), 4)